---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Get Network ID
      include_tasks: task_get_networks.yaml

    - name: Update l7 Firewall Rules
      include_tasks: task_update_networks_l7_firewallrules.yaml
      loop: "{{ Networkid_list }}"
