- name: Get networks appliance firewall l7firewallrules
  cisco.meraki.networks_appliance_firewall_l7_firewall_rules_info:
    networkId: "{{ template_site_id }}"
  register: l7firewallrules

- name: Set Template variable from JSON response
  ansible.builtin.set_fact:
    template_meraki_rules: "{{ l7firewallrules.meraki_response.rules }}"

- name: Update l7firewallrules {{ item }}
  cisco.meraki.networks_appliance_firewall_l7_firewall_rules:
    networkId: "{{ item }}"
    state: present
    rules:
      "{{ template_meraki_rules }}"

- name: Get l7firewallrules {{ item }}
  cisco.meraki.networks_appliance_firewall_l7_firewall_rules_info:
    networkId: "{{ item }}"
  register: updated_l7firewallrules

- name: Show l7firewallrules {{ item }}
  ansible.builtin.debug:
    msg: "{{ updated_l7firewallrules }}"
