---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Update networks appliance firewall l7firewallrules
      cisco.meraki.networks_appliance_firewall_l7_firewall_rules:
        networkId: L_699746792102694137
        state: present
        rules:
        - policy: deny
          type: ipRange
          value: 123.123.123.123/32

    - name: Get networks _appliance _firewall l7firewallrules
      cisco.meraki.networks_appliance_firewall_l7_firewall_rules_info:
        networkId: L_699746792102694137
      register: l7firewallrules

    - name: Show l7firewallrules
      ansible.builtin.debug:
        msg: "{{ l7firewallrules }}"