---
- name: Get networks
  hosts: localhost
  gather_facts: false
  vars:
    org_id: "1575326"

  tasks:
    - name: Get all networks
      cisco.meraki.networks_info:
        organizationId: "{{ org_id }}"
      register: all_networks

    - name: Show all networks
      ansible.builtin.debug:
        msg: "{{ all_networks }}"

    - name: Filtering networks ID
      ansible.builtin.set_fact:
        network_id_list: "{{ all_networks.meraki_response | map(attribute='id') | list }}"

    - name: Show all networks
      ansible.builtin.debug:
        var: network_id_list
