---
- name: Get networks Layer 7 Firewall rules
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get networks _appliance _firewall l7firewallrules
      cisco.meraki.networks_appliance_firewall_l7_firewall_rules_info:
        networkId: L_699746792102695036
      register: l7firewallrules

    - name: Show l7firewallrules
      ansible.builtin.debug:
        msg: "{{ l7firewallrules }}"
