---
- name: Get Organizations ID
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get all Organizations
      cisco.meraki.organizations_info:
      register: result

    - name: Show result
      ansible.builtin.debug:
        msg: "{{ result }}"
